services:
  predictor1:
    build: .
    container_name: matchoracle-predictions
    ports:
      - "3075:3075"
    # volumes:
      # - trained_models:/app/app/trained_models
      # - trained_features:/app/app/configs/important_features
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - appnet

volumes:
  trained_models:
  trained_features:

networks:
  appnet:
    external: true